export const TOGGLE = 'TOGGLE';
export const KURTI_NAUJA_UZSAKYMA = 'KURTI_NAUJA_UZSAKYMA'
;export const PASIRINKTI_UZSAKYMO_EILUTE = 'PASIRINKTI_UZSAKYMO_EILUTE';
;export const TOGGLE_NEW_ROW = 'TOGGLE_NEW_ROW';
;export const SET_INPUT = 'SET_INPUT';
;export const SAVE_ROW = 'SAVE_ROW';
